[package]
name = "bsargeom"
version = "0.1.0"
edition = "2024"

[dependencies.bevy]
version = "0.17"
default-features = false 
features = [
    "bevy_pbr",
    "bevy_render", 
    "bevy_winit",
    "multi_threaded",
    "tonemapping_luts",
    "sysinfo_plugin",
    # "webgl2",
    "webgpu",
    "x11",
    # "zstd"
]

[dependencies]
bevy_panorbit_camera = { version = "0.33", features = ["bevy_egui"] }
bevy_egui = "0.38"
egui_extras = { version = "0.33", features = ["image"] }
image = { version = "0.25", default-features = false, features = ["png"] }
plotters = "0.3"
rustc-hash = "2.1"

# Size optimization (see: https://github.com/johnthagen/min-sized-rust)
[profile.release]
strip = true # = "symbols" Automatically strip symbols from the binary.
lto = true
codegen-units = 1

[profile.web-release]
inherits = "release"
strip = false # = "none" Do not strip symbols from the binary.
opt-level = "z"
